### ISSUE TITLE
SQL Server bulk insert target

### ISSUE THREAD

**Issue by aled** [NLog/NLog.Targets.Database#27]
Hi, I have previously implemented a custom target that uses SQL Server's proprietary bulk insert API. I'm thinking about updating it for inclusion into the main NLog project.

Would this contribution likely to be accepted? I guess it would be in its own project/package, NLog.Extensions.SqlServer or something. 

Cheers, Aled.

**Comment by snakefoot** [comment]
Closing as NLog will not get a Microsoft-SQL-Server specific target. Instead it should be created as seperated nuget-package.

But DatabaseTarget performance can be improved with `isolationLevel="ReadCommitted"` and using `AsyncWrapper`.
