### ISSUE TITLE
Database target: SUpport connectionStringName on .NET Core

### ISSUE THREAD

**Issue by LeonarddeR** [NLog/NLog.Targets.Database#64]
**NLog version**: 4.7.3
**Platform**: .NET Core 3

The [Database target wiki page](https://github.com/nlog/NLog/wiki/Database-target) says about connectionStringName:

> Not supported on NetCore as app.config has been replaced with appsettings.json

While this is true, connection strings are stored in the ConnectionStrings dictionary:
```json
{
  "ConnectionStrings": {
    "SomeName": "Data Source=.;Initial Catalog=SomeDB;Persist Security Info=True;Integrated Security=true;"
  }
}
```

Wouldn't it be possible to support this by retrieving them from the configuration?

**Comment by snakefoot** [comment]
Good idea. The Wiki is open for editing
